In [4]:
# Dependencies and Setup
import pandas as pd
import numpy as np

# File to Load (Remember to Change These)
file_to_load = "Resources/purchase_data.csv"

# Read Purchasing File and store into Pandas data frame
purchase_data = pd.read_csv(file_to_load)
print(purchase_data.head())
purchase_data.describe()

   Purchase ID             SN  Age Gender  Item ID  \
0            0        Lisim78   20   Male      108
1            1    Lisovynya38   40   Male      143
2            2     Ithergue48   24   Male       92
3            3  Chamassasya86   24   Male      100
4            4      Iskosia90   23   Male      131

                                   Item Name  Price
0  Extraction, Quickblade Of Trembling Hands   3.53
1                          Frenzied Scimitar   1.56
2                               Final Critic   4.88
3                                Blindscythe   3.27
4                                       Fury   1.44

       Purchase ID         Age     Item ID       Price
count   780.000000  780.000000  780.000000  780.000000
mean    389.500000   22.714103   92.114103    3.050987
std     225.310896    6.659444   52.775943    1.169549
min       0.000000    7.000000    0.000000    1.000000
25%     194.750000   20.000000   48.000000    1.980000
50%     389.500000   22.000000   93.000000    3.150000
75%     584.250000   25.000000  139.000000    4.080000
max     779.000000   45.000000  183.000000    4.990000

In [5]:
unique_player_count=purchase_data["SN"].nunique()
print(f"Total Unique Players are: {unique_player_count}")

Total Unique Players are: 576

In [6]:
unique_item_count=purchase_data["Item ID"].nunique()
#print(f"Total Unique Items are: {unique_item_count}")

Average_price_val=purchase_data["Price"].mean()
Average_price=f"${Average_price_val:2.3}"

Num_purchases=purchase_data["Purchase ID"].nunique()
#print(Num_purchases)

Tot_revenue=f"${(purchase_data['Price']*1).sum():,}"
#print(Tot_revenue)

df = pd.DataFrame({'Number of Unique Items': [unique_item_count], 'Average Price': [Average_price], 'Number of Purchases': [Num_purchases], 'Total Revenue':[Tot_revenue]}) 
df

   Number of Unique Items Average Price  Number of Purchases Total Revenue
0                     183         $3.05                  780     $2,379.77

# New heading

In [7]:

gender_data2=purchase_data.groupby(["Gender"])["SN"].nunique()
total_gender_count=gender_data2.sum()
gender_data2

Gender
Female                    81
Male                     484
Other / Non-Disclosed     11
Name: SN, dtype: int64

In [10]:

#g_count=2
#df_gender = pd.DataFrame({'Gender':gender_data.index[g_count],'Total Count': [int(gender)], 'Percentage of Players': [int(gender)/total_gender_count*100]}) 
#df_gender 

#pd.options.display.float_format = '{:,.2f}%'.format
df_gender = pd.DataFrame({
                                    "Total Count": gender_data2,
                                    "Percentage": gender_data2/total_gender_count*100
                                   })
df_gender.head()


#df_gender1 = [pd.DataFrame([int(gender)],[int(gender)/total_gender_count],columns=[['Total Count'],['Percentage of Players']]) for gender in gender_data] 

#g_count=0
#for gender in gender_data:
#    print(f"{gender_data.index[g_count]} - {int(gender)} - {int(gender)/total_gender_count:2.2%}")
#    g_count +=1
#df_gender1

                       Total Count  Percentage
Gender
Female                          81   14.062500
Male                           484   84.027778
Other / Non-Disclosed           11    1.909722

In [11]:

gender_data2=purchase_data.groupby(["Gender"])

purchase_count=gender_data2["Purchase ID"].count()

avg_purchase_price=gender_data2["Price"].mean()

total_purchase_price=gender_data2['Price'].sum()

gender_data3=purchase_data.groupby(["Gender","SN"])

avg_per_person=gender_data3["Price"].sum().groupby("Gender").mean()



#pd.options.display.float_format = '{:,.2f}'.format
#print(purchase_count)
#pd.options.display.float_format = '${:,.2f}'.format
#print(avg_purchase_price)
#pd.options.display.float_format = '${:,.2f}'.format
#print(total_purchase_price)

#print(avg_per_person)


#total_gender_count=gender_data2.sum()
#gender_data2

df_gender = pd.DataFrame({          "Purchase Count": purchase_count,
                                    "Average Purchase Price": avg_purchase_price,
                                    "Total Purchase Value":total_purchase_price,
                                    "Avg Total Purchase per Person":avg_per_person
                                   })
df_gender.head()

,Purchase Count,Average Purchase Price,Total Purchase Value,Avg Total Purchase per Person
Gender,,,,
Female,113,3.203009,361.94,4.468395
Male,652,3.017853,1967.64,4.065372
Other / Non-Disclosed,15,3.346000,50.19,4.562727

In [13]:
purchase_data_user_grp=purchase_data.groupby("SN")
purchase_age_data=purchase_data_user_grp["Age"].mean()
print(purchase_age_data.head())
purchase_price_data=purchase_data_user_grp["Price"].sum()
print(purchase_price_data.head())

SN
Adairialis76    16
Adastirin33     35
Aeda94          17
Aela59          21
Aelaria33       23
Name: Age, dtype: int64
SN
Adairialis76    2.28
Adastirin33     4.48
Aeda94          4.91
Aela59          4.32
Aelaria33       1.79
Name: Price, dtype: float64

In [14]:
bins = [0, 9, 14, 19, 24, 29, 34, 39,100]

# Create the names for the four bins
group_labels = ["<10", "10-14", "15-19", "20-24", "25-29","30-34","35-39","40+"]
purchase_age_data1 = pd.DataFrame({"Age": purchase_age_data,"Price":purchase_price_data})
                               

purchase_age_data1["Age Bins"]=pd.cut(purchase_age_data1["Age"], bins, labels=group_labels)

purchase_age_data1.head()

              Age  Price Age Bins
SN
Adairialis76   16   2.28    15-19
Adastirin33    35   4.48    35-39
Aeda94         17   4.91    15-19
Aela59         21   4.32    20-24
Aelaria33      23   1.79    20-24

In [15]:
purchase_age_data2 = purchase_age_data1.groupby("Age Bins")

# Find how many rows fall into each bin
age_count=purchase_age_data2["Age"].count()
total_age=purchase_age_data1["Age"].count()
avg_age_bin=round(purchase_age_data2["Age"].count()/total_age*100,2)

df_age = pd.DataFrame({          "Total Count": age_count,
                                    "Percentage of Players":avg_age_bin
                                   })
df_age

          Total Count  Percentage of Players
Age Bins
<10                17                   2.95
10-14              22                   3.82
15-19             107                  18.58
20-24             258                  44.79
25-29              77                  13.37
30-34              52                   9.03
35-39              31                   5.38
40+                12                   2.08

In [17]:
print(purchase_age_data1.head())

              Age  Price Age Bins
SN
Adairialis76   16   2.28    15-19
Adastirin33    35   4.48    35-39
Aeda94         17   4.91    15-19
Aela59         21   4.32    20-24
Aelaria33      23   1.79    20-24

In [18]:

purchase_age_data2 = pd.DataFrame({"Age": purchase_data["Age"],"SN":purchase_data["SN"],"Price":purchase_data["Price"]})
purchase_age_data2["Age Bins"]=pd.cut(purchase_data["Age"], bins, labels=group_labels)
purchase_age_data2

purchase_data_age_grp2=purchase_age_data2.groupby("Age Bins")
purchase_count2=purchase_data_age_grp2["Age"].count()

avg_purchase_price2=purchase_data_age_grp2["Price"].mean()
avg_purchase_price2


purchase_count2=purchase_data_age_grp2["Age"].count()

avg_purchase_price2=purchase_data_age_grp2["Price"].mean()
total_purchase_price2=purchase_data_age_grp2['Price'].sum()
purchase_data_age_grp3=purchase_age_data2.groupby(["Age Bins","SN"])
avg_per_person2=round(purchase_data_age_grp3["Price"].sum().groupby("Age Bins").mean(),2)

total_purchase_price2


df_age2 = pd.DataFrame({          "Purchase Count": purchase_count2
                                    ,"Average Purchase Price": avg_purchase_price2
                                    ,"Total Purchase Value":total_purchase_price2
                                    ,"Avg Total Purchase per Person":avg_per_person2
                                   })
df_age2

,Purchase Count,Average Purchase Price,Total Purchase Value,Avg Total Purchase per Person
Age Bins,,,,
<10,23,3.353478,77.13,4.54
10-14,28,2.956429,82.78,3.76
15-19,136,3.035956,412.89,3.86
20-24,365,3.052219,1114.06,4.32
25-29,101,2.900990,293.00,3.81
30-34,73,2.931507,214.00,4.12
35-39,41,3.601707,147.67,4.76
40+,13,2.941538,38.24,3.19

In [35]:
purchase_data_user_grp=purchase_data.groupby("SN")
purchase_user_count=purchase_data_user_grp["Purchase ID"].count()
#print(purchase_user_count.head())
purchase_user_avg=purchase_data_user_grp["Price"].mean()
#print(purchase_user_avg.head())
purchase_user_total=purchase_data_user_grp["Price"].sum()
#print(purchase_user_total.head())

df_user2 = pd.DataFrame({          "Purchase Count": purchase_user_count
                                    ,"Average Purchase Price": purchase_user_avg
                                    ,"Total Purchase Value":purchase_user_total
                                   })
df_user2.sort_values("Purchase Count", ascending=False).head()

             Purchase Count  Average Purchase Price  Total Purchase Value
SN
Lisosia93                 5                3.792000                 18.96
Iral74                    4                3.405000                 13.62
Idastidru52               4                3.862500                 15.45
Asur53                    3                2.480000                  7.44
Inguron55                 3                3.703333                 11.11

In [37]:
purchase_data_user_grp=purchase_data.groupby("Item ID")
purchase_item_count2=purchase_data_user_grp["Item ID"].count()
#print(purchase_user_count.head())
purchase_item_avg2=purchase_data_user_grp["Price"].mean()
#print(purchase_user_avg.head())
purchase_item_total2=purchase_data_user_grp["Price"].sum()
#print(purchase_user_total.head())
purchase_item_name2=purchase_data_user_grp['Item Name'].first()


df_item3 = pd.DataFrame({         "Item Name": purchase_item_name2
                                 ,"Purchase Count": purchase_item_count2
                                    ,"Average Purchase Price": purchase_item_avg2
                                    ,"Total Purchase Value":purchase_item_total2
                                   })
df_item3=df_item3.sort_values("Purchase Count", ascending=False)
df_item3=df_item3.style.format({'Average Purchase Price': "${:2.2f}", 'Total Purchase Value': '{:+.2f}'})
df_item3.head()